export const MFE_HOOK_ACTIONS = {
  SET_IS_LOADED: "SET_IS_LOADED",
  SET_ENTRY: "SET_ENTRY",
  SET_DEPENDENCIES: "SET_DEPENDENCIES",
  SET_DEPENDENCY_QUEUE: "SET_DEPENDENCY_QUEUE"
};

export default MFE_HOOK_ACTIONS;
